@php
    $meta = $meta ?? [];
    $rangeStart = $meta['range_start'] ?? '—';
    $rangeEnd = $meta['range_end'] ?? '—';
    $generatedAt = $meta['generated_at'] ?? date('d/m/Y h:i A');
    $generatedById = $meta['generated_by_id'] ?? null;
    $generatedBy = trim((string) ($meta['generated_by'] ?? ''));
    $rowCount = $rowCount ?? (isset($rows) ? count($rows) : null);
@endphp
<div class="meta"> 
    <strong>Report range:</strong> {{ $rangeStart }} – {{ $rangeEnd }}<br>
    <strong>Generated:</strong> {{ $generatedAt }}<br>
    <strong>Generated by (User ID):</strong>
    @if ($generatedById)
        {{ $generatedById }}@if ($generatedBy !== '') — {{ $generatedBy }}@endif
    @else
        —
    @endif
    <br>
    @if ($rowCount !== null)
        <strong>Total Rows:</strong> {{ $rowCount }}
    @endif
</div>
